#!/bin/bash

is-ginko() {
    code=$1
    sleep 1
    curl -s "https://gincode.com/bank_$code" |
        nkf | grep '<title' | grep "銀行($code)" >/dev/null
}

suffix() {
    code=$1
    type=$2
    if [ "$type" = "ginko" ]; then
        if is-ginko "$code"; then
            echo "銀行"
        else
            :
        fi
    else
        :
    fi
}

FILE=temp/banktype.list
NUM=$(cat $FILE | wc -l)
I=0

cat $FILE |
    while read code type; do
        echo "{\"$code\": \"$(suffix $code $type)\"}"
        I=$((I + 1))
        printf "\r${I} / ${NUM}" >&2
    done |
    jq -M -s '. | add'
